theme: minima
title: codejj1 Portfolio
author: codejj1
email: codejj1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Github/resume portfolio of projects and studies by codejj1!

# social links
twitter_username: codejj1
github_username:  codejj1

show_excerpts: true # set to false to remove excerpts on the homepage
